### ISSUE TITLE
Margin problems

### ISSUE THREAD

**Issue by tejasmorkar** [devscollab/sandbox#17]
The entire margin of the webpage is not correct. A margin should be added to the text shown. Also, the last line in the website can be made better in terms of visibility.

# TODO

Add margin to the steps list given on the webpage

Increase the font of the last line "Edits: ..."

![image](https://user-images.githubusercontent.com/35477326/90668402-b1c4d180-e26d-11ea-922d-fbf47e3bca25.png)

**Comment by bhavansh** [comment]
About the last line should i make it as a list of all those who have contributed

**Comment by tejasmorkar** [comment]
Yes, that'll be better!
